"""empty message

Revision ID: ba51aa53c706
Revises: 75eca79df5c1
Create Date: 2022-02-27 13:51:06.207793

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba51aa53c706'
down_revision = '75eca79df5c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='students')
    op.drop_table('students')
    op.drop_index('name', table_name='classes')
    op.drop_table('classes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', mysql.VARCHAR(collation='utf8_bin', length=32), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_bin', length=32), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'classes', ['name'], unique=False)
    op.create_table('students',
    sa.Column('id', mysql.VARCHAR(collation='utf8_bin', length=32), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_bin', length=32), nullable=False),
    sa.Column('class_id', mysql.VARCHAR(collation='utf8_bin', length=32), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name='students_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'students', ['name'], unique=False)
    # ### end Alembic commands ###
